# fly.toml app configuration file generated for hashapp on 2025-05-18T11:16:28+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hashapp'
primary_region = 'sin'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[build]
  dockerfile = "Dockerfile"

[env]
PORT = "8080"